### ISSUE TITLE
Dynamic management of security groups

### ISSUE THREAD

**Issue by fededido** [hopandfork/teacup-storm#3]
Currently we statically refer to security groups created by the EC2 Management Console, as it is still a draft implementation. In the future, it should be allowed to create and assign security groups based on the needs of the application deployed in the server.

**Comment by grussorusso** [comment]
PR #6 moved configuration of security groups into YAML file. We could now work on a script to perform required setup on AWS and prepare lines to be pasted into configuration file.

**Comment by grussorusso** [comment]
#12 solves this issue.

**Comment by fededido** [comment]
Resolved by #12
